package models

import "time"

type Team struct {
	id               string
	name             string
	logo             string
	performanceCount uint32
}

type Athlete struct {
	id      uint32
	name    string
	surname string
	dob     time.Time
}

type Meet struct {
	id             uint32 // autogenerated
	code           string // fetched
	name           string
	location       string
	date           time.Time
	isChampionship bool
}

type Race struct {
	id        uint32 // autogenerated
	code      string // fetched
	meetId    string
	distance  uint16 // istg se includono le ultramaratone vado personalmente in Viale Tiziano 70 a Roma ad assicurarmi che non superino i 65535 metri
	division  string // TODO: replace with enum
	category  string // TODO: replace with enum
	boat      string // TODO: replace with enum
	level     string // TODO: replace with enum
	startTime time.Time
}

type Heat struct {
	id        uint32
	index     uint8
	raceId    uint32
	startTime time.Time
	isResult  bool
}

type Performance struct {
	id        uint32
	heatId    uint32
	teamId    string
	lane      uint8 // ora sicuro fanno le gare da 300 atleti
	placement uint8 // se qualche cristiano osa arrivare 256esimo verrá menato dal sottoscritto.
	timeMs    uint32
	status    string // TODO: replace with enum
}
